### ISSUE TITLE
Rev_A Fixes

### ISSUE THREAD

**Issue by adkinsjd** [lab11/permamote#3]
- [x] Silk labels for Secondary Cell and its polarity
 - [x] Silk labels for primary cell
 - [x] silk labels for solar panel and polarity
 - [x] Connect LBST to NRF for incoming energy measurement

**Comment by nealjack** [comment]
There are already silk labels for the solar panel, primary, and secondary cell. The secondary silk is on the back of the board. The solar input is on the front, but admittedly pretty obscured by things around it. The primary silkscreen is also hard to distinguish.

**Comment by nealjack** [comment]
- [ ] Update RF passives to newer spec
- [ ] Add decoupling cap to DEC5
