### ISSUE TITLE
Rev_B Issues

### ISSUE THREAD

**Issue by adkinsjd** [lab11/permamote#4]
- [ ] A better reset button (just so you don't forget)

**Comment by nealjack** [comment]
Might as well add a power switch too

**Comment by adkinsjd** [comment]
Hmm I don't know about this for the same reasons we didn't add one to
Signpost

**Comment by nealjack** [comment]
The only reason would be that if the programmer had previously been set up
for debugging/rtt, it puts the NRF52840 into a high power state that can
only be disabled by a power reset or resetting the programmer and
reflashing.
